name: build
on: [push]
jobs:
  build_job: # job name
    runs-on: ubuntu-22.04
    steps:
      - name: Use JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # here the actual build starts
      - name: Standard Checkout
        uses: actions/checkout@v3.2.0

      - name: Build with Maven
        run: mvn -B verify